/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../consts/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../consts/index`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useInsets`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useTheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useToggle`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useLocalization`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mods)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(super)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../consts/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../consts/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useInsets`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useTheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useToggle`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useLocalization`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(mods)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(super)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../consts/colors${`?${string}` | `#${string}` | ''}` | `/../consts/index${`?${string}` | `#${string}` | ''}` | `/../hooks/useInsets${`?${string}` | `#${string}` | ''}` | `/../hooks/useTheme${`?${string}` | `#${string}` | ''}` | `/../hooks/useToggle${`?${string}` | `#${string}` | ''}` | `/../hooks/useLocalization${`?${string}` | `#${string}` | ''}` | `/../hooks/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(mods)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(super)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../consts/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../consts/index`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useInsets`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useTheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useToggle`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useLocalization`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mods)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(super)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
